### ISSUE TITLE
(RuntimeError) Webdriver call status code 404 for post request

### ISSUE THREAD

**Issue by wlminimal** [HashNuke/hound#175]
Hello.
I am testing in Phoenix.
using phantomjs --wd
and I ran tests, it shows this

**Comment by tuvistavie** [comment]
Hi, thanks for reporting.

I could not reproduce, what version of Phantomjs are you using?
Could you please give a minimal example to reproduce?

Here is the example I tried:

```elixir
use Hound.Helpers  
Hound.start_session()
navigate_to "https://tuvistavie.com/"
find_element(:class, "panel-cover__title") |> visible_text()
```

**Comment by kkweon** [comment]
The code snippet was from the book: [Mastering Phoenix](https://shankardevy.com/phoenix-book/)
I was also stuck at the same page and googling led me here, :smile: 

Anyway,  the problem occurs when the `phantomjs` is installed through `apt-get`.
Installing the latest `phantomjs` from the [official page](http://phantomjs.org/download.html) fixed the issue.

This issue can be closed.

**Comment by denispeplin** [comment]
I was having same issue. After I've removed a package from official repository and downloaded it from official download page, issue got fixed. Both versions are same, `2.1.1`. OS is `Ubuntu 16.04.4 LTS`, 64 bit.

**Comment by lessless** [comment]
I have same problem:

```
phantomjs     | [INFO  - 2019-09-08T13:34:48.811Z] Session [6dc64860-d23d-11e9-8f59-95606648a3f2] - Session.negotiatedCapabilities - {"browserName":"phantomjs","version":"2.1.1","driverName":"ghostdriver","driverVersion":"1.2.0","platform":"linux-unknown-64bit","javascriptEnabled":true,"takesScreenshot":true,"handlesAlerts":false,"databaseEnabled":false,"locationContextEnabled":false,"applicationCacheEnabled":false,"browserConnectionEnabled":false,"cssSelectorsEnabled":true,"webStorageEnabled":false,"rotatable":false,"acceptSslCerts":false,"nativeEvents":true,"proxy":{"proxyType":"direct"},"phantomjs.page.settings.userAgent":"Mozilla/5.0 (Windows NT 6.1) AppleWebKit/538.1 (KHTML, like Gecko) PhantomJS/2.1.1 Safari/538.1"}
phantomjs     | [INFO  - 2019-09-08T13:34:48.811Z] SessionManagerReqHand - _postNewSessionCommand - New Session Created: 6dc64860-d23d-11e9-8f59-95606648a3f2
phantomjs     | [ERROR - 2019-09-08T13:34:49.326Z] RouterReqHand - _handle.error - {"line":264,"sourceURL":"phantomjs://code/webelement_request_handler.js","stack":"_postValueCommand@phantomjs://code/webelement_request_handler.js:264:52\n_handle@phantomjs://code/webelement_request_handler.js:72:30\n_reroute@phantomjs://code/request_handler.js:61:20\n_handle@phantomjs://code/session_request_handler.js:120:42\n_reroute@phantomjs://code/request_handler.js:61:20\n_handle@phantomjs://code/router_request_handler.js:78:46"}
phantomjs     |
phantomjs     |   phantomjs://platform/console++.js:263 in error
```

my `docker-compose.yml`:

```
version: '3'
services:
  dockerhost:
    image: qoomon/docker-host
    cap_add: [ 'NET_ADMIN', 'NET_RAW' ]
    restart: on-failure
  phantomjs:
    depends_on: [ dockerhost ]
    image: wernight/phantomjs:latest
    container_name: phantomjs
    restart: always
    ports:
      - "8910:8910"
    command: "phantomjs --webdriver=8910 --ignore-ssl-errors=true --ssl-protocol=any"

    ```
