### ISSUE TITLE
[error] GenServer Hound.SessionServer terminating ** (Poison.SyntaxError) Unexpected token: u 

### ISSUE THREAD

**Issue by turnabout4** [HashNuke/hound#77]
I'm trying to integration test of phoenix framework on CircleCI.
Tests has successed on my local environment(mac with chromedriver). but on CicleCi, an error has occurred.

Best regards.

---

ERLANG_VERSION="18.2.1"
ELIXIR_VERSION="v1.2.2"

circle.yml
```
...

  post:
    # selenium 
    - wget http://selenium-release.storage.googleapis.com/2.44/selenium-server-standalone-2.44.0.jar
    - java -jar selenium-server-standalone-2.44.0.jar:
        background: true
    # install chromedriver
    - wget https://chromedriver.storage.googleapis.com/2.20/chromedriver_linux64.zip
    - unzip chromedriver_linux64.zip
    # run chromedriver
    - ./chromedriver --url-base=wd/hub --port=9515  --verbose --log-path=$CIRCLE_ARTIFACTS/chromedriver.log:
        background: true
```

mix.exs
```
...
  defp deps do
    [
      {:phoenix, "~> 1.1.2"},
      {:phoenix_ecto, "~> 2.0"},
      {:postgrex, ">= 0.0.0", override: true},
      {:phoenix_html, "~> 2.3"},
      {:phoenix_live_reload, "~> 1.0", only: :dev},
      {:cowboy, "~> 1.0"},
      {:comeonin, "~> 2.0"},
      {:guardian, "~> 0.9.0"},
      {:credo, "~> 0.2", only: [:dev, :test]},
      {:ex_machina, "~> 0.6.1"},
      {:exactor, "~> 2.2.0"},
      {:hound, "~> 0.8"},
      {:mix_test_watch, "~> 0.2", only: :dev},
      {:exrm, "~> 0.19.9"}
     ]
  end
...
```

config.exs

```
...
config :hound, driver: "chrome_driver"
...
```

error message
```
[error] GenServer Hound.SessionServer terminating
** (Poison.SyntaxError) Unexpected token: u
    (poison) lib/poison/parser.ex:56: Poison.Parser.parse!/2
    (poison) lib/poison.ex:83: Poison.decode!/2
    (hound) lib/hound/response_parsers/chrome_driver.ex:7: Hound.ResponseParsers.ChromeDriver.parse/3
    (hound) lib/hound/request_utils.ex:53: Hound.RequestUtils.send_req/4
    (hound) lib/hound/session_server.ex:67: Hound.SessionServer.handle_call/3
    (stdlib) gen_server.erl:629: :gen_server.try_handle_call/4
    (stdlib) gen_server.erl:661: :gen_server.handle_msg/5
    (stdlib) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
23:25:27.289 [error] GenServer Hound.SessionServer terminating
** (Poison.SyntaxError) Unexpected token: u
    (poison) lib/poison/parser.ex:56: Poison.Parser.parse!/2
    (poison) lib/poison.ex:83: Poison.decode!/2
    (hound) lib/hound/response_parsers/chrome_driver.ex:7: Hound.ResponseParsers.ChromeDriver.parse/3
    (hound) lib/hound/request_utils.ex:53: Hound.RequestUtils.send_req/4
    (hound) lib/hound/session_server.ex:67: Hound.SessionServer.handle_call/3
    (stdlib) gen_server.erl:629: :gen_server.try_handle_call/4
    (stdlib) gen_server.erl:661: :gen_server.handle_msg/5
    (stdlib) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
23:25:27.290 [error] GenServer Hound.SessionServer terminating
** (Poison.SyntaxError) Unexpected token: u
    (poison) lib/poison/parser.ex:56: Poison.Parser.parse!/2
    (poison) lib/poison.ex:83: Poison.decode!/2
    (hound) lib/hound/response_parsers/chrome_driver.ex:7: Hound.ResponseParsers.ChromeDriver.parse/3
    (hound) lib/hound/request_utils.ex:53: Hound.RequestUtils.send_req/4
    (hound) lib/hound/session_server.ex:67: Hound.SessionServer.handle_call/3
    (stdlib) gen_server.erl:629: :gen_server.try_handle_call/4
    (stdlib) gen_server.erl:661: :gen_server.handle_msg/5
    (stdlib) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
23:25:27.290 [error] GenServer Hound.SessionServer terminating
** (Poison.SyntaxError) Unexpected token: u
    (poison) lib/poison/parser.ex:56: Poison.Parser.parse!/2
    (poison) lib/poison.ex:83: Poison.decode!/2
    (hound) lib/hound/response_parsers/chrome_driver.ex:7: Hound.ResponseParsers.ChromeDriver.parse/3
    (hound) lib/hound/request_utils.ex:53: Hound.RequestUtils.send_req/4
    (hound) lib/hound/session_server.ex:67: Hound.SessionServer.handle_call/3
    (stdlib) gen_server.erl:629: :gen_server.try_handle_call/4
    (stdlib) gen_server.erl:661: :gen_server.handle_msg/5
    (stdlib) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
```
